# Generated by Django 4.1.4 on 2022-12-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('createdAt', models.DateField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateField(auto_now_add=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'etiquetas',
                'ordering': ['-nombre'],
            },
        ),
    ]
