# Generated by Django 4.1.4 on 2022-12-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_Creacion_Tabla_Tareas_y_Realaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='descripcion',
            field=models.TextField(default='nada'),
            preserve_default=False,
        ),
    ]
